language: python
python:
- '3.7'
install:
- pip install flake8
script:
- flake8 flake8_gl_codeclimate scripts tests
- python -m unittest discover -s ./tests -v
deploy:
  provider: pypi
  user: awelzel
  on:
    tags: true
  password:
    secure: Tvflg17t5HR2bbGFxXfwnErLezNED/OAGt+GbT7V0/JUEm06+nQ0omMNE/zaUaARbifTgDACxHsf3aAopWUswxWHHytPi3GuBmfRaBPNQNfXW9FD6Xjn6XJkF26NsqEpg4A80LQz/4yDcJjBL26exfBsuhCrGmya9XY6FjtKkx1bL02IQxdSowjwRFa01ePzK31AnMJTlIFePa2LONHKHFxaLniojTKH6WUD8gOV+BWvz/N/UPf8V6LtfhnLu2ivrF3cFOmJnxqWQ8GKdRQU4MhIDLEXemgJpISxyzXhapWHXIxW2JhZ2CjKTCOUjb9In61bPtnIZ1actCrrmvvHF/6iGRRRxAZ1mQK0XpkCcqIju0ZsuHkq0Ek5JqCoS4ud76sHUAPiWu0YlsbXcJlWcVq58cKE1S38+CSNHIGHoKB3NkIBOsZsHQpU+qkKxs1vgjUSkgMG/keMeR+kCb6st4uaRsjQcABCsYmYdSfkGc8LeFQwvhWwyx1S2+BxUJ/9FObVvb03GP1y7JqLDqDm5e24VxPwlFN58qgsnawpjkB6cj8TqlYS3M5tK7r4/3qbYjpjGrEN7d1zW6kPWEaczxjoomcHB7Pg2yp17GYvDEmEoFfaRHBabw+wLPpo5MfWDaCMI/NFc4411uP0qI5LYPpq1oxpS2z1baZl2m41K7Y=
